import { sendVisitingEmail } from '@/utils/sendVisitingEmail'
import './globals.css'
import "bootstrap-icons/font/bootstrap-icons.css"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  sendVisitingEmail({durration : 0})
  return (
    <html lang="en">
      <head></head>
      <body ><div className='appContainer' >{children}</div></body>
    </html>
  )
}
